bind = $mainMod, Q, exec, $terminal

bind = $mainMod, C, exec, ~/.config/hypr/derpy/binds/kill.sh

bind = $mainMod, M, exit,

bind = $mainMod, D, exec, subl

bind = $mainMod, E, exec, $fileManager

bind = $mainMod, V, togglefloating,

bind = $mainMod, F, fullscreen

bind = $mainMod, R, exec, $menu

bind = $mainMod, P, pseudo, # dwindle

bindm = $mainMod, mouse:272, movewindow

bindm = $mainMod, mouse:273, resizewindow

bind = , code:107, exec, grimblast copy area
