
#browser/waterfox opacities
$browser_class = waterfox
windowrule {
	name = waterfox_conf_base
	match:class = $browser_class
	opacity = 0.7 override 0.7 override 1 override
	workspace = 4 silent
}
windowrule = opacity 1 override 0.7 override 1 override, match:title (.*)(- YouTube)(.*)
windowrule = opacity 0.8 override 0.7 override 1 override, match:title (.*)(HiAnime.to)(.*)
# I dont use these but if i ever release, or ever do use them, here:
windowrule = opacity 0.9 override 0.7 override 1 override, match:title (Prime Video:)(.*)
windowrule = opacity 0.9 override 0.7 override 1 override, match:title (Netflix)(.*)
windowrule = opacity 0.9 override 0.7 override 1 override, match:title (.*)(- Watch on Crunchyroll)(.*)

#terminal/kitty
windowrule {
	name = kitty_conf
	match:class = $terminal
	opacity = 0.6
	float = true
	size = 1350 750
	center = true
}

#nemo
windowrule {
	name = nemo_conf
	match:class = nemo
	opacity = 0.7
	float = true
	size = 1350 775
	center = true
}

#vesktop
windowrule {
	name = vesktop_conf
	match:class = vesktop
	workspace = 5 silent
	opacity = 0.8
}

#steam
windowrule {
	name = steam_conf
	match:class = steam
	pseudo = true
	size = 1450 850
	monitor = DP-1
	workspace = 2 silent
	opacity = 0.7
}
#prism
windowrule = opacity 0.7, match:class (org.prismlauncher.PrismLauncher)

#sublime
windowrule {
	name = sublime_text_conf
	match:class = sublime_text
	float = true
	size = 1350 750
	center = true
	opacity = 0.7
}
#Steam Apps
windowrule {
	name = steam_apps_conf
	match:class = (steam_app)(.*)
	fullscreen = true
	workspace = 2
	render_unfocused = true
}
# ABD Downloadmanger
windowrule {
	name = download_manager_conf
	match:class = com-abdownloadmanager-desktop-AppKt
	opacity = 0.7
}
windowrule {
	name = settings_download_manager_conf
	match:class = com-abdownloadmanager-desktop-AppKt
	match:title = negative:^AB Download Manager$
	center = true
	float = true
	size = 1600 900
}

#qbit
windowrule = opacity 0.7, match:class (org.qbittorrent.qBittorrent)

#vlc/mpv
windowrule = opacity 1 override 0.7 override 1 override, match:title (.*)(- VLC media player)

windowrule = suppress_event maximize, match:class .*


# Fix some dragging issues with XWayland

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# 3 workspaces per monitor

workspace = 1, monitor:DP-1, persistent:true

workspace = 2, monitor:DP-1, persistent:true

workspace = 3, monitor:DP-1, persistent:true

workspace = 4, monitor:DP-2, persistent:true

workspace = 5, monitor:DP-2, persistent:true

workspace = 6, monitor:DP-2, persistent:true
